baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'This is Mostafa'
permalink: /blog/:year/:month/:day/:title
google_analytics_id: null
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile_.svg"
  desktop: "images/logo/logo_.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'theme by <a class="zerostatic" href="https://github.com/zerostaticthemes/hugo-serif-theme">Robert Austin</a>'

seo:
  meta_og_title: "This is Mostafa"
  meta_og_type: "website"
  meta_og_url: "thisismostafa.site"
  meta_og_description: "Personal homepage of Mostafa"
  meta_twitter_card: "summary"
  meta_twitter_site: "@TweetAtMostafa"
  meta_twitter_creator: "@TweetAtMostafa"

collections:
  cv:
    output: true
    permalink: /cv/:path/
  team:
    output: true
    permalink: /team/:path/

defaults:
  - scope:
      type: cv
    values:
      layout: skill
      bodyClass: page-skill-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
